from dataclasses import dataclass
from typing import List, Optional
from urllib.parse import urlparse

from playwright.sync_api import (
    Page,
    Request,
    Response,
)


@dataclass(frozen=True)
class RequestRecord:
    """Store information about one browser request."""

    method: str
    url: str
    resource_type: str
    is_navigation_request: bool


@dataclass(frozen=True)
class ResponseRecord:
    """Store information about one browser response."""

    status: int
    url: str
    resource_type: str


@dataclass(frozen=True)
class FailedRequestRecord:
    """Store information about one failed browser request."""

    method: str
    url: str
    resource_type: str
    failure: Optional[str]


class NetworkRecorder:
    """Record first-party network traffic generated by a page."""

    def __init__(
        self,
        first_party_domain: str = "automationexercise.com",
    ) -> None:
        self.first_party_domain = first_party_domain

        self.requests: List[RequestRecord] = []
        self.responses: List[ResponseRecord] = []
        self.failed_requests: List[
            FailedRequestRecord
        ] = []

    def start(
        self,
        page: Page,
    ) -> None:
        """Start listening to page network events."""

        page.on(
            "request",
            self._record_request,
        )

        page.on(
            "response",
            self._record_response,
        )

        page.on(
            "requestfailed",
            self._record_failed_request,
        )

    def _is_first_party(
        self,
        url: str,
    ) -> bool:
        """Check whether a URL belongs to the tested website."""

        hostname = (
            urlparse(url).hostname
            or ""
        )

        return (
            hostname == self.first_party_domain
            or hostname.endswith(
                f".{self.first_party_domain}"
            )
        )

    def _record_request(
        self,
        request: Request,
    ) -> None:
        """Record one first-party request."""

        if not self._is_first_party(
            request.url
        ):
            return

        self.requests.append(
            RequestRecord(
                method=request.method,
                url=request.url,
                resource_type=request.resource_type,
                is_navigation_request=(
                    request.is_navigation_request()
                ),
            )
        )

    def _record_response(
        self,
        response: Response,
    ) -> None:
        """Record one first-party response."""

        if not self._is_first_party(
            response.url
        ):
            return

        self.responses.append(
            ResponseRecord(
                status=response.status,
                url=response.url,
                resource_type=(
                    response.request.resource_type
                ),
            )
        )

    def _record_failed_request(
        self,
        request: Request,
    ) -> None:
        """Record one first-party request that failed."""

        if not self._is_first_party(
            request.url
        ):
            return

        self.failed_requests.append(
            FailedRequestRecord(
                method=request.method,
                url=request.url,
                resource_type=request.resource_type,
                failure=request.failure,
            )
        )